### PR TITLE
fix(versions): update Activiti/activiti-cloud-full-chart versions into master

### PR DESCRIPTION
**Pull request by alfresco-build-user**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed helm dependency: `activiti-cloud-dependencies` to: `7.1.923`

### CODE REVIEW

**Comment by alfresco-build-user** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind helm activiti-cloud-dependencies 7.1.923 runtime-bundle 7.1.923 activiti-cloud-connector 7.1.923 activiti-cloud-query 7.1.923 activiti-cloud-modeling 7.1.923

**Comment by alfresco-build-user** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind helm activiti-cloud-identity 0.0.22

**Comment by alfresco-build-user** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind helm activiti-cloud-dependencies 7.1.924 runtime-bundle 7.1.924 activiti-cloud-connector 7.1.924 activiti-cloud-query 7.1.924 activiti-cloud-modeling 7.1.924

**Comment by almerico** [comment]
[UpdateBot](https://github.com/jenkins-x/updatebot) commands:

    updatebot push-version --kind helm runtime-bundle 7.1.915 activiti-cloud-connector 7.1.915 activiti-cloud-query 7.1.915 activiti-cloud-modeling 7.1.915 --repo https://github.com/Activiti/activiti-cloud-application

**Pull request merged**
