### PR TITLE
fix(versions): update Activiti/activiti-cloud-full-chart versions into master

### PR DESCRIPTION
**Pull request by alfresco-build**
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed helm dependency: `common` to: `7.5.0-alpha.5`

### CODE REVIEW

**Comment by atchertchian** [comment]
not sure why 7.4.0 versions are being updated here?

**Comment by atchertchian** [comment]
apparently triggered by https://github.com/Activiti/activiti-cloud-common-chart/runs/7561487839?check_suite_focus=true

**Comment by atchertchian** [comment]
apparently triggered by closing https://github.com/Activiti/activiti-cloud-full-chart/pull/798 by mistake

**Comment by atchertchian** [comment]
status: pre-commit hooks currently failing on:
```
helm dep up ./charts/activiti-cloud-full-example 
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://codecentric.github.io/helm-charts" chart repository
...Successfully got an update from the "https://activiti.github.io/activiti-cloud-helm-charts" chart repository
...Successfully got an update from the "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/" chart repository
...Successfully got an update from the "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/" chart repository
...Successfully got an update from the "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami/" chart repository
Error: can't get a valid version for repositories common, common, common, common, common, common. Try changing the version constraint in Chart.yaml

Helm Lint................................................................Failed
- hook id: helm-lint
- exit code: 123

helm lint ./charts/activiti-cloud-full-example 
==> Linting ./charts/activiti-cloud-full-example
Error:  templates/: template: activiti-cloud-full-example/templates/realm-secret.yaml:7:8: executing "activiti-cloud-full-example/templates/realm-secret.yaml" at <include "common.labels" .>: error calling include: template: no template "common.labels" associated with template "gotpl"
```
The same failure was already visible on previous PR for the same changes at https://github.com/Activiti/activiti-cloud-full-chart/pull/798, see https://github.com/Activiti/activiti-cloud-full-chart/runs/7074470714?check_suite_focus=true (run on June 27)

**Review by igdianov — APPROVED** [review]

**Pull request merged**
